### PR TITLE
[Build] change dependency to nnstreamer api @open sesame 02/17 18:27

### PR DESCRIPTION
**Pull request by jaeyun-jung**
Now api repo is newly added, change dependency to ml-inference-api.

Signed-off-by: Jaeyun <jy1210.jung@samsung.com>

### CODE REVIEW

**Review by zhoonit — APPROVED** [review]
LGTM!

**Comment by jaeyun-jung** [comment]
PR updated - build script for Tizen and Ubuntu.

**Review by lhs8928 — APPROVED** [review]
Seems need to fix CI issues
Other than that looks good to me.

**Review by myungjoo — APPROVED** [review]
LGTM.

You will need to ignore Tizen build errors and need to do GROUP-SR when everything is ready.
You will need to synchronize with @again4you

**Review by again4you — APPROVED** [review]
LGTM!

**Pull request merged**
