### PR TITLE
[README] Fix typo error in README

### PR DESCRIPTION
**Pull request by baek2sm**
Fixed the typo error in the title of the paper bellow.
- NNTrainer: Light-Weight On-Device Training Framework, arXiv, 2022

Signed-off-by: seungbaek <sb92.hong@samsung.com>

### CODE REVIEW

**Review by gichan-jang — APPROVED** [review]
Nice catch, LGTM.

**Review by DonghakPark — APPROVED** [review]
LGTM!

**Review by lhs8928 — APPROVED** [review]
LGTM

**Comment by baek2sm** [comment]
I'm sorry, below was mislabeled as bellow in the commit message.

**Review by songgot — APPROVED** [review]
LGTM

**Review by jihochu — APPROVED** [review]
Nice catch! :+1:

**Review by jijoongmoon — APPROVED** [review]
LGTM

**Pull request merged**
