### PR TITLE
[ layer ] Enable mha gtest and match version @open sesame 06/04 13:01

### PR DESCRIPTION
**Pull request by skykongkong8**
- Current mha layer at nntrainer/layer is not for general use, but implemented solely for LLaMA support.
- In order to run unittest for mha layer:
1. rollback current mha layer to previous one
2. move current implemenation to Application/LLaMA
3. enable unittest

**Self evaluation:**
1. Build test:     [X]Passed [ ]Failed [ ]Skipped
2. Run test:     [X]Passed [ ]Failed [ ]Skipped

### CODE REVIEW

**Review by SeoHyungjun — APPROVED** [review]
LGTM

**Review by lhs8928 — APPROVED** [review]
LGTM

**Comment by skykongkong8** [comment]
> LGTM

But I wonder... won't this PR hinder some dependencies in other LLaMAs using mha? Just asking.

**Review by DonghakPark — APPROVED** [review]
LGTM!

**Comment by jijoongmoon** [comment]
Currently, MHA layer in the layers directory is rollbacked. I would like to know if you tested the LLaMA Application with this a custom MHA layer as in this PR. Please confirm it first.

**Review by jijoongmoon — APPROVED** [review]
LGTM

**Pull request merged**
