### PR TITLE
[header] add missing headers @open sesame 10/02 11:44

### PR DESCRIPTION
**Pull request by lhs8928**
- Added missing header

### CODE REVIEW

**Review by EunjuYang — APPROVED** [review]
LGTM

**Review by DonghakPark — APPROVED** [review]
LGTM!! but check CI (commit msg length maybe)

**Review by djeong20 — APPROVED** [review]
LGTM!

**Review by skykongkong8 — APPROVED** [review]
LGTM

**Comment by DonghakPark** [comment]
Please Rebase (upstream/main), https://github.com/nnstreamer/nntrainer/pull/2741 resolve cache_test_cast issue

**Review by SeoHyungjun — APPROVED** [review]
LGTM

**Review by baek2sm — APPROVED** [review]
LGTM

**Pull request merged**
