### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by robotboyfriend**
Hello,

I improved the spelling within the README to improve project documentation clarity.

Great project! Keep up the good work!

Peace and Love.

### CODE REVIEW

**Review by jihochu — APPROVED** [review]
LGTM

**Review by songgot — APPROVED** [review]
LGTM

**Comment by myungjoo** [comment]
Please refer to the DCO link: https://github.com/nnstreamer/nntrainer/pull/1606/checks?check_run_id=3812461600
We need your sign (via git sign-off) with your actual name and email address, which allows everyone on earth can use your code with the given license (and you've agreed with https://github.com/nnstreamer/nntrainer/blob/main/CODE_OF_CONDUCT.md )

**Comment by myungjoo** [comment]
This PR is no longer relevant.

**Pull request closed without merging**
