### PR TITLE
[Docs] Fix doxygen

### PR DESCRIPTION
**Pull request by JuYeong0413**
- Fix some doxygen errors
- Fix author email typo /cc @zhoonit 

Signed-off-by: Juyeong Lee <2jy22@naver.com>

### CODE REVIEW

**Comment by JuYeong0413** [comment]
Sorry for the frequent force-pushing.
The remaining doxygen errors are about missing `@brief` tags.
Other things like syntax errors or typos are fixed.

**Review by zhoonit — APPROVED** [review]
Awesome. Thank you for the fix :-)

**Review by kparichay — APPROVED** [review]
LGTM

**Review by jijoongmoon — APPROVED** [review]
LGTM

**Pull request merged**
