### PR TITLE
[Loss] Remove Empty KLD Loss files @open sesame 10/18 12:10

### PR DESCRIPTION
**Pull request by DonghakPark**
Currently, the KLD Loss file has only the function name and is empty.
Therefore, I will remove this file now and implement it after retesting with test cases and verification in the next issue 

- #2757 

**Self evaluation:**
1. Build test:	 [X]Passed [ ]Failed [ ]Skipped
2. Run test:	 [X]Passed [ ]Failed [ ]Skipped

### CODE REVIEW

**Review by EunjuYang — APPROVED** [review]

**Review by EunjuYang — COMMENTED** [review]
Don't you need to update `meson.build`, which ccontains `kld_loss_layer.cpp`?

**Comment by DonghakPark** [comment]
> Don't you need to update `nntrainer/layers/loss/meson.build`, which contains `kld_loss_layer.cpp`?

Yes, indeed! Thank you for double-checking it

**Review by SeoHyungjun — APPROVED** [review]
LGTM

**Review by baek2sm — APPROVED** [review]
LGTM

**Pull request merged**
