### PR TITLE
[GPU/OPENCL] RMSNorm Accuracy Fix

### PR DESCRIPTION
**Pull request by pallaviNNT**
Accuracy issue observed while running SRLLM on GPU due to wrong gamma values being used.
Fixed the same

### CODE REVIEW

**Comment by jijoongmoon** [comment]
Could check the static checker  CI issue? 
And also have to check wether we do need the header inclusion of RMSNormCL in layer.h https://github.com/nnstreamer/nntrainer/blob/32d901cee3c913a27e95ce81923266f6de7a063b/api/ccapi/include/layer.h#L314

**Review by djeong20 — APPROVED** [review]

**Review by EunjuYang — APPROVED** [review]
Nice catch!
What about updating the comment for the alpha as well? (one for each ~~channel~~)

**Review by skykongkong8 — APPROVED** [review]
LGTM!

**Review by jijoongmoon — APPROVED** [review]
LGTM

**Pull request merged**
