### PR TITLE
Fix typo in docs

### PR DESCRIPTION
**Pull request by kimhan0515**
Fix typos for some docs
- README.md and docs/configuration-ini.md: simple typo
- Applications/MNIST/README.md: typo and duplicate image

**Self evaluation:**
1. Build test:     [X]Passed [ ]Failed [ ]Skipped
2. Run test:     [X]Passed [ ]Failed [ ]Skipped

Signed-off-by: Hanbyeol Kim kimhan0515@snu.ac.kr

### CODE REVIEW

**Review by DonghakPark — APPROVED** [review]
Thank you for your PR!
Nice Catch 👍

**Review by skykongkong8 — APPROVED** [review]
Nice catch! Thanks for you contribution :)

**Review by EunjuYang — APPROVED** [review]
Thank you for your contribution! :) LGTM!

**Review by jijoongmoon — APPROVED** [review]
LGTM

**Pull request merged**
