### PR TITLE
[Application] mnist: Fix tf example

### PR DESCRIPTION
**Pull request by jihochu**
Modified for tensorflow 2.10.0.

Signed-off-by: Jiho Chu <jiho.chu@samsung.com>

### CODE REVIEW

**Review by DonghakPark — APPROVED** [review]
LGTM!
But "tf.compat.v1" also Deprecated in Tensorflow 2.x Version.
I think We will fix Tensorflow Example

**Review by songgot — APPROVED** [review]
LGTM

**Review by lhs8928 — APPROVED** [review]
LGTM

**Comment by jihochu** [comment]
> LGTM! But "tf.compat.v1" also Deprecated in Tensorflow 2.x Version. I think We will fix Tensorflow Example

compat.v1 is checked as deprecated for some, but still working for many.
Toally deprecation would take long time. If you know the schedule of it, please let us know.

**Review by jijoongmoon — APPROVED** [review]
LGTM

**Pull request merged**
