### PR TITLE
[CI] Add PR review from clang-format

### PR DESCRIPTION
**Pull request by djeong20**
This PR enables the GitHub actions bot to suggest changes based on the clang-format directly.

**Changes proposed in this PR:**
- Add format-review options to enable Pull Request reviews from clang-format.
- Upgrade the cpp-linter version to 2.9.0 to meet minimum version requirements.

**Self-evaluation:**
1. Build test: [X]Passed [ ]Failed [ ]Skipped
2. Run test:   [X]Passed [ ]Failed [ ]Skipped

### CODE REVIEW

**Review by DonghakPark — APPROVED** [review]
Good, it will guide for who are not familiar with clang-format how to edit it.

**Review by skykongkong8 — APPROVED** [review]
LGTM

**Comment by djeong20** [comment]
In order for the github-actions bot to properly comment, write permission should be granted to the GITHUB_TOKEN.

ref: https://cpp-linter.github.io/cpp-linter-action/permissions/

Would it be possible for nntrainer to have **Send write tokens to workflows from pull requests** setting? @myungjoo @jijoongmoon

**Review by EunjuYang — APPROVED** [review]
LGTM! 👍

**Review by SeoHyungjun — APPROVED** [review]
LGTM

**Pull request merged**
