### PR TITLE
[ccapi/nntrainer] Add getters for `ml::train::Model` states

### PR DESCRIPTION
**Pull request by JRazek**
### **Commits to be reviewed in this PR**

<details>
<summary> [ccapi/nntrainer] Add getters for compiled, initialized and loadedFromConfig </summary>
  
  ## Changed
  1. Added getter for a `nntrainer::NeuralNetwork::compiled` variable.
  2. Added getter for a `nntrainer::NeuralNetwork::initialized` variable.
  3. Added getter for a `nntrainer::NeuralNetwork::loadedFromConfig` variable.
</details>

### CODE REVIEW

**Comment by myungjoo** [comment]
Please write a summary in commit message. It is empty and it makes it hard to maintain codes in the future.

**Review by lhs8928 — APPROVED** [review]
LGTM

**Review by jijoongmoon — APPROVED** [review]
This is good to be CC APIs to get the state of Neural Network Model. LGTM.

**Comment by jijoongmoon** [comment]
Thanks for the PR. But PR summary should have more detail and be more formal.
Here is an example you can use,

## Dependency of the PR


## Commits to be reviewed in this PR


<details><summary>[Network Graph] Split max_exec_order</summary><br />

This patch split max_exec_order to three part.

1. graph_exec_end: graph execution end
2. backward_iter_end: end node of backward operation
3. forward_iter_end: end node of the forward operation

**Self evaluation:**
1. Build test: [X]Passed [ ]Failed [ ]Skipped
2. Run test: [X]Passed [ ]Failed [ ]Skipped

Signed-off-by: Jihoon Lee <jhoon.it.lee@samsung.com>

</details>



<details><summary>[ExecOrder] Add exec order control and fix inference</summary><br />

This patch add exec order control and reduce memory overhead of saving
inference result

exec order cotrol has two part

1. Additional exec order. This enable graph to add some exec order.
2. Expose bit. This enables request to be visible after the end of the
execution.

**Self evaluation:**
1. Build test: [X]Passed [ ]Failed [ ]Skipped
2. Run test: [X]Passed [ ]Failed [ ]Skipped

Signed-off-by: Jihoon Lee <jhoon.it.lee@samsung.com>

</details>



<details><summary>[Tensor Pool] Add expose/persist concept</summary><br />

This patch add expose/persist concept to the tensor pool and manager.

When a tensor is exposed, this means that the tensor is gauranteed to
remain valid max_exec where max_exec is the value passed along allocateTensors(max_exec);

**Self evaluation:**
1. Build test: [X]Passed [ ]Failed [ ]Skipped
2. Run test: [X]Passed [ ]Failed [ ]Skipped

Signed-off-by: Jihoon Lee <jhoon.it.lee@samsung.com>

</details>

resolves #1832

**Pull request merged**
