### PR TITLE
action/ubuntu: fp16 on/off handled by matrix

### PR DESCRIPTION
**Pull request by myungjoo**
To de-dup scripts handling fp16-enabled and fp16-disabled cases for meson-clean build, add another matrix entry.

Reference: https://github.com/nnstreamer/nntrainer/pull/2641/files#r1646986341

CC: @heka1024

### CODE REVIEW

**Review by heka1024 — COMMENTED** [review]
I think I read in https://github.com/nnstreamer/nntrainer/issues/2560#issuecomment-2082273173 that the Fp16 build was supposed to be optional. But I think this pull request make a build on fp16 as required. Should we make it required?

**Comment by myungjoo** [comment]
> I think we said in [#2560 (comment)](https://github.com/nnstreamer/nntrainer/issues/2560#issuecomment-2082273173) that the Fp16 build should be optional. But I think this pull request make a build on fp16 as required. Should we make it required?

fp16 build should be kept optional. Users should be able to enable/disable fp16 for their own build.

fp16 integration should be kept mandatory. Any commit should NEVER break fp16 support, which will keep users being able to enable/disable fp16 for their own build. Without this mandate, users won't be able to enable fp16 in the near future.

**Review by heka1024 — APPROVED** [review]
It seems much nicer. Thank you!

**Review by DonghakPark — APPROVED** [review]
it's much better !! LGTM!!

**Review by djeong20 — APPROVED** [review]
LGTM

**Review by SeoHyungjun — APPROVED** [review]
LGTM!

**Pull request merged**
