### PR TITLE
[coverity] fix coverity issues

### PR DESCRIPTION
**Pull request by EunjuYang**
This PR fixes coverity issues of `auto_causes_copy`
	- 1739360
	- 1740106

Self-evaluation:

Build test: [X]Passed [ ]Failed [ ]Skipped
Run test: [X]Passed [ ]Failed [ ]Skipped

### CODE REVIEW

**Review by jihochu — APPROVED** [review]
LGTM

**Review by djeong20 — APPROVED** [review]
LGTM

**Review by lhs8928 — APPROVED** [review]
LGTM

**Review by skykongkong8 — APPROVED** [review]
LGTM. Re-submit to avoid postbuild fail

**Pull request merged**
