### PR TITLE
[Skeleton] Add resnet application skeleton

### PR DESCRIPTION
**Pull request by zhoonit**
- [Skeleton] Add resnet application skeleton

```
This patch adds resnet application skeleton

**Self evaluation:**
1. Build test: [X]Passed [ ]Failed [ ]Skipped
2. Run test: [X]Passed [ ]Failed [ ]Skipped

Signed-off-by: Jihoon Lee <jhoon.it.lee@samsung.com>

```

### CODE REVIEW

**Comment by kparichay** [comment]
I wonder about #941.

**Comment by zhoonit** [comment]
> I wonder about #941. Do you think you can work on top of it or discuss once with @jijoongmoon about it.

We've discussed offline to make a new PR. Thanks for sharing the concern :)

**Comment by kparichay** [comment]
So what about #941 then?

**Comment by zhoonit** [comment]
Some part of it will be copied and pasted from #941 with author.

**Review by kparichay — APPROVED** [review]
LGTM

**Review by jijoongmoon — APPROVED** [review]
LGTM

**Pull request merged**
