### PR TITLE
[docs] add "how-to-create-model" tutorial document

### PR DESCRIPTION
**Pull request by baek2sm**
I have added a tutorial document on how users can build their own models using NNTrainer.

The current tutorial is just the most basic draft, and it needs updating.
It seems that the API needs to be updated to use easily,
as setting up the data by the user is very inconvenient for now.
(So in this example, it uses random data generator.
so.. user couldn't learn how to train using a real data.)

I also added this tutorial link to the README on the first page,
and since the list of maintainers and contributors currently occupies too much space,
I moved this part to the bottom of the README.

Signed-off-by: Seungbaek Hong <sb92.hong@samsung.com>

### CODE REVIEW

**Review by skykongkong8 — APPROVED** [review]
Would be a great guide for beginners!
LGTM!

**Review by Hyoungsukim — APPROVED** [review]
lgtm

**Review by djeong20 — APPROVED** [review]
LGTM

**Review by jijoongmoon — APPROVED** [review]
LGTM!

**Pull request merged**
