### PR TITLE
[Application] Add Mixed precision Application @open sesame 11/27 09:33

### PR DESCRIPTION
**Pull request by DonghakPark**
Add Mixed Precision example on Application 
- this example can guide developer to handle fp16 example
- we can test & eval our model end-to-end 
- we can optimize base on this model

**Self evaluation:**
1. Build test:   [X]Passed [ ]Failed [ ]Skipped
2. Run test:     [X]Passed [ ]Failed [ ]Skipped

Signed-off-by: Donghak PARK <donghak.park@samsung.com>

### CODE REVIEW

**Review by myungjoo — APPROVED** [review]

**Review by EunjuYang — APPROVED** [review]
LGTM

**Review by SeoHyungjun — APPROVED** [review]
LGTM!

**Review by djeong20 — APPROVED** [review]
nice work!

**Review by skykongkong8 — APPROVED** [review]
Nice work!

**Pull request merged**
