### PR TITLE
[transfer learning] Enable test on ubuntu

### PR DESCRIPTION
**Pull request by kparichay**
Enable testing of the trained model on ubuntu

Signed-off-by: Parichay Kapoor <pk.kapoor@samsung.com>

### CODE REVIEW

**Review by zhoonit — COMMENTED** [review]
this will need nnstreamer as a dependency.
Could you check the meson dependency as well? 

It seems like that only when `enable-nnstreamer-tensor-filter` is on we add nnstreamer as a dependency.

**Comment by kparichay** [comment]
`capi-nnstreamer` should itself add `nnstreamer` as dependency. So, we shouldn't add `nnstreamer` as dependency as `nnstreamer` might change their dependency which makes nntrainer code dependent on nnstreamer code.

**Comment by jijoongmoon** [comment]
I think we need to support this example if there is no nnstreamer support.

**Review by jijoongmoon — APPROVED** [review]
LGTM

**Comment by kparichay** [comment]
> I think we need to support this example if there is no nnstreamer support. Except that LGTM

I will add a check on nnstreamer support and only then use nnstreamer related code.

**Review by zhoonit — APPROVED** [review]
LGTM

**Pull request merged**
