### PR TITLE
[Trivial] Disable cpp-linter action's clang-format

### PR DESCRIPTION
**Pull request by DonghakPark**
We currently perform a Clang format check during our static checks.

The CPP-Linter we are using is from the Action Market and occasionally produces different results even when the same version is specified. This reduces efficiency for developers, so only the static check with more detailed logs will be left and the CPP-Linter function will be disabled.

However, the existing Linter function will remain.

**Self evaluation:**
1. Build test:	 [X]Passed [ ]Failed [ ]Skipped
2. Run test:	 [X]Passed [ ]Failed [ ]Skipped

### CODE REVIEW

**Review by baek2sm — APPROVED** [review]
LGTM

**Review by lhs8928 — APPROVED** [review]
LGTM

**Review by SeoHyungjun — APPROVED** [review]
LGTM

**Review by djeong20 — APPROVED** [review]
LGTM

**Review by skykongkong8 — APPROVED** [review]
LGTM

**Comment by EunjuYang** [comment]
Dooray! Failure Notice



  
  
    
    
  
  
    
        Failure Notice
    
  
  
    
        
        Your message sent to
          
***@***.***
          has failed to be delivered.
        
        
          Please refer to the below for details.
        
    
  
  
    
      
        
          
            * Recipient : 
***@***.***
          
          
            * Sent time : 
2024-03-29T07:33:24
          
          
            * Subject : 
Re: [nnstreamer/nntrainer] [Trivial] Disable cpp-linter action's clang-format (PR #2522)
          
          
            
              
                * Remote host said : 
              
              
                
대외비/기밀 메일은 외부 계정으로 발송이 제한되어 일부 메일 발송 실패(수신자가 전달 설정한 경우 포함)
                
              
            
                      
          
        
      
    
  
  
    
        
          This message was sent from a notification-only address that cannot accept incoming email.
          For more information, please contact           ***@***.***
        
    
  
  
    
        © Dooray!.

**Pull request merged**
