### PR TITLE
[ Document ] Add daily build status @open sesame 02/05 10:55

### PR DESCRIPTION
**Pull request by jijoongmoon**
Add daily build status in readme

**Self evaluation:**
1. Build test:	 [X]Passed [ ]Failed [ ]Skipped
2. Run test:	 [X]Passed [ ]Failed [ ]Skipped

Signed-off-by: jijoong.moon <jijoong.moon@samsung.com>

### CODE REVIEW

**Comment by gichan-jang** [comment]
I think it would be good to add a daily-build badge.
http://nnsuite.mooo.com/nntrainer/ci/daily-build/badge/daily_build_badge.svg

**Comment by jijoongmoon** [comment]
> I think it would be good to add a daily-build badge.
> http://nnsuite.mooo.com/nntrainer/ci/daily-build/badge/daily_build_badge.svg

done! Thanks.

**Review by myungjoo — APPROVED** [review]
Great!

**Review by gichan-jang — APPROVED** [review]
LGTM

**Review by kparichay — APPROVED** [review]
LGTM

**Pull request merged**
