### PR TITLE
[CI] Add cpp file format checker

### PR DESCRIPTION
**Pull request by DonghakPark**
This patch adds a Github Action workflow to check cpp file format
- this file imported from deviceMLOps.MLAgent
- this file use cpp_linter marketplace actions

**Self evaluation:**
1. Build test:	 [X]Passed [ ]Failed [ ]Skipped
2. Run test:	 [X]Passed [ ]Failed [ ]Skipped

### CODE REVIEW

**Review by djeong20 — COMMENTED** [review]
quick question. current TAOS/pr-prebuild-clang specify the exact line to fix. would this work the same?

**Comment by DonghakPark** [comment]
> quick question. current TAOS/pr-prebuild-clang specify the exact line to fix. would this work the same?

This action based on marketplace gitaction : https://github.com/marketplace/actions/c-c-linter
And according to explain they give line by line feedback !

**Review by SeoHyungjun — APPROVED** [review]
As far as I know, the official extension is yaml.
I understand that yml was created because the extension is limited to 3 characters in Windows.
How about changing it to yaml?

**Comment by DonghakPark** [comment]
> As far as I know, the official extension is yaml. I understand that yml was created because the extension is limited to 3 characters in Windows. How about changing it to yaml?

I totally agree with you . The three-character limit is no longer a meaningful rule. 
However, since the default value for adding a new action in GitHub is defined as YML, all the GitAction files in NNTrafter have been unified to YML. I believe it is for wider compatibility and GitHub uses YML as the default value for GitAction.

What do you think about conforming to the default settings on Github or is it better to change official express ?

**Review by djeong20 — APPROVED** [review]

**Review by jijoongmoon — APPROVED** [review]
LGTM

**Pull request merged**
