### PR TITLE
Example to reproduce #427

### PR DESCRIPTION
**Pull request by zhoonit**
This patch reproduces #427

Each data contains 62720 feature + 2 label = 250,888 byte (62722 * 4)

There are 5 data ready for trainingSet and validationSet(1,254,440 byte
each)

Please do not review or merge this PR

**Self evaluation:**
1. Build test: [X]Passed [ ]Failed [ ]Skipped
2. Run test: [X]Passed [ ]Failed [ ]Skipped

**How to run**
- Change dir to source root of the example (You can use `chdir` inside code for convenience)
- run without args

Signed-off-by: Jihoon Lee <jhoon.it.lee@samsung.com>

### CODE REVIEW

**Comment by zhoonit** [comment]
This example is still nondeterministic.

```bash
$ ./Applications/toy_classification/toy_classification 
#1/1 - Training Loss: 0.580394 >> [ Accuracy: 40% - Validation Loss : 0.762923 ] 

$ ./Applications/toy_classification/toy_classification 
#1/1 - Training Loss: 0.580394 >> [ Accuracy: 40% - Validation Loss : 0.762923 ] 

$ ./Applications/toy_classification/toy_classification 
run model failed %d-1073741824
```

**Comment by kparichay** [comment]
Can you do a small addon work - 
create a loop to ruin this application a thousand times and then just log here how many times it fails.

@jijoongmoon Can you please check this.

**Comment by zhoonit** [comment]
> Can you do a small addon work -
> create a loop to ruin this application a thousand times and then just log here how many times it fails.
> 
> @jijoongmoon Can you please check this.

Will do today.

**Comment by zhoonit** [comment]
result with 10000 times.

success 3017
construct fail 0
compile fail 0
run fail 6983
unknown 0

**Comment by kparichay** [comment]
> result with 10000 times.
> 
> success 3017
> construct fail 0
> compile fail 0
> run fail 6983
> unknown 0

Thanks.
@jijoongmoon Can you please take a look at this with the databuffer. The reproducible example by @zhoonit is easy to understand.

**Comment by zhoonit** [comment]
Resolved with #525

**Pull request closed without merging**
