### PR TITLE
[GitAction] Fix Duplicate Approvals @open sesame 04/03 14:45

### PR DESCRIPTION
**Pull request by DonghakPark**
## In this PR
Fix Duplicate Approval
- now git action count all approval
- For example someone Approve PR --> Update PR --> Approve Again then they count 2
- For example CI Approve PR every time they success then gitaction count them all

## Workflow
The given Git Action code performs the following tasks
1. Uses the curl command to call the GitHub REST API and retrieve a list of reviews for the given pull request in the repository.
2. Uses the jq command to filter the reviews based on whether their state is "APPROVED".
3. Extracts the login names of the users who wrote each of the filtered reviews.
4. Uses the unique function to filter out only the unique login names, removing any duplicates.
5. Calculates the length of the resulting list of unique login names, giving the count of unique users who have approved the pull request.

**Therefore, this code removes any duplicate approvals, counting each unique user only once, even if they have approved more than once.**

### CODE REVIEW

**Review by baek2sm — APPROVED** [review]
LGTM

**Comment by jijoongmoon** [comment]
Could you do the rebase?

**Comment by DonghakPark** [comment]
> Could you do the rebase?

[FIX] I did rebase

**Review by songgot — APPROVED** [review]
LGTM

**Pull request merged**
