### PR TITLE
[Fix] api feature check problem

### PR DESCRIPTION
**Pull request by zhoonit**
## Commits to be reviewed in this PR

<details><summary>[Fix] api feature check problem</summary><br />

This is an emergency measure for feature check is failing inside
unittest of gbs build.

Also enabled ml_inference test

**Self evaluation:**
1. Build test: [X]Passed [ ]Failed [ ]Skipped
2. Run test: [X]Passed [ ]Failed [ ]Skipped

Signed-off-by: Jihoon Lee <jhoon.it.lee@samsung.com>

</details>

### CODE REVIEW

**Review by myungjoo — CHANGES_REQUESTED** [review]
Why did you rename ml_tizen_set_feature_state?

**Comment by zhoonit** [comment]
> Why did you rename ml_tizen_set_feature_state?

This is being done to avoid (potential) violation of one definition rule. 
There is `ml_tizen_set_feature_state` is used at ml api side, recently got _ as a prefix.
https://github.com/nnstreamer/api/blob/181305562ea838ae276c1031118e2afad5099b14/c/src/ml-api-common-tizen-feature-check.c#L58.

If we are to do similar patch (adding a prefix) it will violate ODR.

`ml_train_tizen_set_feature_state` or `_ml_train_tizen_set_feature_state` looked as a reasonable choice as dedicated prefix in this repo is `ml_train_`.

**Review by kparichay — APPROVED** [review]
LGTM

**Comment by myungjoo** [comment]
> > Why did you rename ml_tizen_set_feature_state?
> 
> This is being done to avoid (potential) violation of one definition rule. There is `ml_tizen_set_feature_state` is used at ml api side, recently got _ as a prefix. https://github.com/nnstreamer/api/blob/181305562ea838ae276c1031118e2afad5099b14/c/src/ml-api-common-tizen-feature-check.c#L58.
> 
> If we are to do similar patch (adding a prefix) in this repo, it will violate ODR.
> 
> `ml_train_tizen_set_feature_state` or `_ml_train_tizen_set_feature_state` looked a reasonable choice as dedicated prefix in this repo is `ml_train_`.

Ah.. I thought this is github.com/nnstreamer/api.git :)

Ok. LGTM

**Review by myungjoo — APPROVED** [review]

**Review by jaeyun-jung — APPROVED** [review]

**Review by jijoongmoon — APPROVED** [review]
LGTM

**Pull request merged**
