### PR TITLE
[Profile] Add annotate for memory profiling @open sesame 10/20 07:09

### PR DESCRIPTION
**Pull request by jihochu**
It adds several annotations for memory profiling.
Each of them can help to teach profile steps.

Signed-off-by: Jiho Chu <jiho.chu@samsung.com>

It depends on #1965

### CODE REVIEW

**Comment by jihochu** [comment]
Example result for annotation:
```
                                                  DEALLOC                      0                      0                       CacheElem(/tmp/weight_pool2705558) #17                      9                                                                                                                                                        
                                                    ALLOC                     40                     40                       CacheElem(/tmp/weight_pool2705558) #18                                                                                                                                                                               
                                                  DEALLOC                      0                      0                       CacheElem(/tmp/weight_pool2705558) #18                      8                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                   
TRAIN START                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                   
Forwarding for layer: inputlayer                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                   
Forwarding for layer: conv2d_c1_layer                                                                                                                                                                                                                                                                                                              
                                                    ALLOC                  57600                  57600                       CacheElem(/tmp/tensor_pool2705558) #4                                                                                                                                                                                
                                                    ALLOC                    600                  58200                       CacheElem(/tmp/weight_pool2705558) #1                                                                                                                                                                                
                                                    ALLOC                 442368                 500568                       CacheElem(/tmp/tensor_pool2705558) #2                                                                                                                                                                                
                                                    ALLOC                     24                 500592                       CacheElem(/tmp/weight_pool2705558) #2                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                   
Forwarding for layer: conv2d_c1_layer/activation_realized                                                                                                                                                                                                                                                                                          
                                                  DEALLOC                      0                 499992                       CacheElem(/tmp/weight_pool2705558) #1                   4847                                                                                                                                                         
                                                  DEALLOC                      0                 499968                       CacheElem(/tmp/weight_pool2705558) #2                    202                                                                                                                                                         
                                                  DEALLOC                      0                 442368                       CacheElem(/tmp/tensor_pool2705558) #4                   5190 
```

**Comment by jijoongmoon** [comment]
I think you could also add the tensor name since nntrainer tensor has it's own name. And it might help to debug.

**Review by jijoongmoon — APPROVED** [review]
LGTM.  But could you check whether all file changes are included in this PR once again?

**Comment by jihochu** [comment]
> It could be done in later pr though, but I think you could also add the tensor name since nntrainer tensor has it's own name. And it might help to debug.

>LGTM. But could you check whether all file changes are included in this PR once again?

@jijoongmoon I'm working for layer name in this PR. please hold on merging.

**Comment by jihochu** [comment]
@jijoongmoon,
I misunderstood that you mentioned "layer name".  the layer name is already inserted in this PR.
The 'tensor name' (you really mentioned) needs to change Profiling feature. (maybe tensor name column is necessary).
So, It cannot be covered in this PR.
I'll add tensor name feature for profiliing in later PR. sorry for cofusing.

**Review by DonghakPark — APPROVED** [review]
LGTM!!

**Pull request merged**
