### PR TITLE
[Filter] util to get nth info

### PR DESCRIPTION
**Pull request by jaeyun-jung**
Use util function to get nth tensor-info ptr.
Also, remove unnecessary header include in filter subplugin.

### CODE REVIEW

**Review by DonghakPark — APPROVED** [review]
LGTM!

**Review by djeong20 — APPROVED** [review]
LGTM! Is it because using the util function is safer than directly accessing nth info?

**Comment by jaeyun-jung** [comment]
> LGTM! Is it because using the util function is safer than directly accessing nth info?

tensors-info struct has only 16 array slots, others (max number of tensors is 256) are allocated memory.
If the number of tensors are larger than 16, out-of-bound error.

**Review by skykongkong8 — APPROVED** [review]

**Comment by DonghakPark** [comment]
Please Rebase (upstream/main), https://github.com/nnstreamer/nntrainer/pull/2741 resolve cacheLoader_test_case issue

**Review by lhs8928 — APPROVED** [review]
LGTM

**Review by baek2sm — APPROVED** [review]
LGTM

**Pull request merged**
