### PR TITLE
Troubleshooting installation steps.

### PR DESCRIPTION
**Pull request by meteozay**
Some of the errors observed during installation and compilation of NNTrainer, and their working solutions.

### CODE REVIEW

**Comment by kparichay** [comment]
@meteozay Thanks for the PR.
I request you to please sign the commit and add a commit message body to pass the CI errors.

**Comment by meteozay** [comment]
Fixing commit errors.

**Comment by meteozay** [comment]
Deleting troubleshooting branch.

**Comment by zhoonit** [comment]
please fork the repository and make a branch from the forked repository :)

**Pull request closed without merging**
