### PR TITLE
[Wait for #2172][Tensor] Support NHWC for add, Pow and subtract @open sesame 04/07 20:08

### PR DESCRIPTION
**Pull request by jijoongmoon**
This PR enables and validate NHWC computation in add, pow and subtract
tensor operation. It also includes the unit test cases.

**Self evaluation:**
1. Build test:	 [X]Passed [ ]Failed [ ]Skipped
2. Run test:	 [X]Passed [ ]Failed [ ]Skipped

Signed-off-by: jijoong.moon <jijoong.moon@samsung.com>

### CODE REVIEW

**Review by DonghakPark — APPROVED** [review]
LGTM!

**Review by SeoHyungjun — APPROVED** [review]
LGTM!

Like the comment in the previous commit, I think it would be nice to modify it with getTensorDim!

**Review by baek2sm — APPROVED** [review]
LGTM

**Comment by jijoongmoon** [comment]
This is included #2238

**Pull request closed without merging**
