### PR TITLE
[Conv2d/Test] Add more test

### LINKED ISSUE #1054: Cleanup conv2d layer
Handle issue from review #1042. 

- [ ] move commented code upward.
- [ ] remove channel argument
- [ ] Add conv negative test
- [ ] Add more test

### PR DESCRIPTION
**Pull request by zhoonit**
- [Conv2d/Test] Add more test

```
This patch adds test suggested at #1042

Resolves #1054

**Self evaluation:**
1. Build test: [X]Passed [ ]Failed [ ]Skipped
2. Run test: [X]Passed [ ]Failed [ ]Skipped

Signed-off-by: Jihoon Lee <jhoon.it.lee@samsung.com>

```

### CODE REVIEW

**Review by kparichay — APPROVED** [review]
LGTM
do we have unittests where stride and padding are both set uneven?

**Comment by zhoonit** [comment]
> do we have unittests where stride and padding are both set uneven?

no, we have uneven kernel, input. This makes effective kernel size uneven anyway.

**Comment by kparichay** [comment]
> > do we have unittests where stride and padding are both set uneven?
> 
> no, we have uneven kernel, input. This makes effective kernel size uneven anyway.

I am worried about appropriate output sizes and padding being done in uneven scenario. Will it be covered in uneven kernel?

**Comment by zhoonit** [comment]
> I am worried about appropriate output sizes and padding being done in uneven scenario. Will it be covered in uneven kernel?

Yes, computationally it's equivalent

**Review by jijoongmoon — APPROVED** [review]
LGTM

**Pull request merged**
