### PR TITLE
[Application] Setup meson file for libyolov2_loss_layer.so @open sesame 09/13 18:48

### PR DESCRIPTION
**Pull request by baek2sm**
Setup meson file for making libyolov2_loss_layer.so in yolo v2 application.

**Self evaluation:**
1. Build test:	 [X]Passed [ ]Failed [ ]Skipped
2. Run test:	 [X]Passed [ ]Failed [ ]Skipped

### CODE REVIEW

**Review by songgot — APPROVED** [review]
LGTM.
now, below code(main.cpp) is not necessary, Thank you.
```
  auto &app_context = nntrainer::AppContext::Global();

  try {
    app_context.registerFactory(nntrainer::createLayer<custom::ReorgLayer>);
  } catch (std::invalid_argument &e) {
    std::cerr << "failed to register reorg layer, reason: " << e.what()
              << std::endl;
    return 1;
  }

  try {
    app_context.registerFactory(
      nntrainer::createLayer<custom::YoloV2LossLayer>);
  } catch (std::invalid_argument &e) {
    std::cerr << "failed to register loss layer, reason: " << e.what()
              << std::endl;
    return 1;
  }
```

**Review by Hyoungsukim — APPROVED** [review]
lgtm

**Review by djeong20 — APPROVED** [review]
LGTM

**Comment by songgot** [comment]
Thank you, have a nice day!

**Pull request merged**
