### PR TITLE
[bnlayer] Batch norm layer bug fix

### PR DESCRIPTION
**Pull request by kparichay**
This patch provides bug fix to the initialization of the batch norm
values.

Signed-off-by: Parichay Kapoor <pk.kapoor@samsung.com>

### CODE REVIEW

**Comment by kparichay** [comment]
@zhoonit I could not get genModelTests.py to work with this. Please take a look.

**Comment by kparichay** [comment]
@zhoonit The patch passes, please once check that genModelTests.py is passing the correct parameters in order, and this isn't just on-incidentally passing.

**Review by jijoongmoon — APPROVED** [review]
LGTM

**Review by zhoonit — APPROVED** [review]
LGTM, I'll check the test issue soon.

**Pull request merged**
