### PR TITLE
[Application] Add multi_input dataloader example @open sesame 09/15 16:08

### PR DESCRIPTION
**Pull request by baek2sm**
Added multi-input dataloader example application.

**Self evaluation:**
1. Build test:	 [X]Passed [ ]Failed [ ]Skipped
2. Run test:	 [X]Passed [ ]Failed [ ]Skipped

Signed-off-by: Seungbaek Hong <sb92.hong@samsung.com>

### CODE REVIEW

**Review by SeoHyungjun — APPROVED** [review]
LGTM

**Review by DonghakPark — APPROVED** [review]
LGTM!

**Review by skykongkong8 — COMMENTED** [review]
LGTM!

**Review by Hyoungsukim — APPROVED** [review]
lgtm

**Comment by myungjoo** [comment]
@songgot : This appears to be a good reference for datarepo-src/sink. Please take a look.

**Review by jijoongmoon — APPROVED** [review]
LGTM

**Pull request merged**
