### PR TITLE
[README] Modify the image url

### PR DESCRIPTION
**Pull request by lhs8928**
Modify the image url from absolute path to relative path

Signed-off-by: hyeonseok lee <hs89.lee@samsung.com>

### CODE REVIEW

**Comment by zhoonit** [comment]
Could you check this out for other locations as well??

**Comment by lhs8928** [comment]
> Could you check this out for other locations as well??

Okay I will.

**Review by zhoonit — APPROVED** [review]
LGTM :)

**Review by jijoongmoon — APPROVED** [review]
LGTM

**Pull request merged**
