### PR TITLE
[Applications] Refactor applications @open sesame 09/11 19:06

### PR DESCRIPTION
**Pull request by kparichay**
Refactor applications
- Classification -> TransferLearning/CIFAR_classification
- Training -> TransferLearning/Draw_classification
- mnist -> MNIST
- Delete TIZEN_CAPI as it overlaps with the unittests without even checking the final accuracy
Correspondingly update meson and some README.md

**Self evaluation:**
1. Build test: [x]Passed [ ]Failed [ ]Skipped
2. Run test: [x]Passed [ ]Failed [ ]Skipped

Signed-off-by: Parichay Kapoor <pk.kapoor@samsung.com>

### CODE REVIEW

**Comment by zhoonit** [comment]
Python generated file have sneaked into our repo. Could you delete `Applications/MNIST/Tensorflow/__pycache__/dataset.cpython-35.pyc`?

**Comment by kparichay** [comment]
> Python generated file have sneaked into our repo. Could you delete `Applications/MNIST/Tensorflow/__pycache__/dataset.cpython-35.pyc`?

added.

**Comment by jijoongmoon** [comment]
I think Training_Keras.py.pk should be deleted.

**Review by jijoongmoon — APPROVED** [review]
LGTM

**Comment by kparichay** [comment]
> I think Training_Keras.py.pk should be deleted.

done.

**Comment by jijoongmoon** [comment]
Did you test for all platform ? andorid, ubuntu and others? Cause due to the filesize, we could not check the ci.

**Comment by kparichay** [comment]
> Did you test for all platform ? andorid, ubuntu and others? Cause due to the filesize, we could not check the ci.

I think the CI still checks. I checked on android and Ubuntu. I will check tizen locally tomorrow.

**Comment by kparichay** [comment]
> Did you test for all platform ? andorid, ubuntu and others? Cause due to the filesize, we could not check the ci.

Done.

**Review by zhoonit — APPROVED** [review]
LGTM

**Pull request merged**
