### PR TITLE
Handle NO_CATCH issue

### PR DESCRIPTION
**Pull request by lhs8928**
Added missing try-catch statement
resolve 457589

Signed-off-by: hyeonseok lee <hs89.lee@samsung.com>

### CODE REVIEW

**Review by zhoonit — APPROVED** [review]
LGTM after fixing ci issue

**Comment by zhoonit** [comment]
deep code retry

**Comment by zhoonit** [comment]
deepcode retry

**Review by kparichay — APPROVED** [review]
LGTM

**Pull request merged**
