### PR TITLE
[ CI ] Temporal Fix for the CI about NNStreamer Backone

### PR DESCRIPTION
**Pull request by jijoongmoon**
Temporarily, we have to turn off the nnstreamer backbone until some issue is fixed.

**Self evaluation:**
1. Build test:	 [X]Passed [ ]Failed [ ]Skipped
2. Run test:	 [X]Passed [ ]Failed [ ]Skipped

Signed-off-by: jijoong.moon <jijoong.moon@samsung.com>

### CODE REVIEW

**Comment by gichan-jang** [comment]
How about disabling only tests that temporarily fail?
For example, 
```
TEST_F(DISABLED_mlInference, singleshot_p) {
```

**Review by gichan-jang — APPROVED** [review]
LGTM.
I posted the issue about this PR. We will fix this soon.
https://github.com/nnstreamer/nnstreamer/issues/3957

**Comment by jijoongmoon** [comment]
> How about disabling only tests that temporarily fail? For example,
Done. Thanks.

**Review by songgot — APPROVED** [review]
LGTM

**Review by jihochu — APPROVED** [review]
LGTM

**Pull request merged**
