### PR TITLE
[Trivial] Rename yolo -> yolo v2 @open sesame 05/10 19:54

### PR DESCRIPTION
**Pull request by baek2sm**
- To prevent confusion, the name of YOLOv2 implementation was changed from
YOLO to YOLOv2.

- Apply pep8 style guide

Signed-off-by: Seungbaek Hong <sb92.hong@samsung.com>

### CODE REVIEW

**Review by skykongkong8 — APPROVED** [review]
LGTM

**Review by djeong20 — APPROVED** [review]
nice work. LGTM

**Review by DonghakPark — APPROVED** [review]
LGTM!

**Comment by DonghakPark** [comment]
Please ignore Pylint fail : it looks like ci error

**Comment by baek2sm** [comment]
> Please ignore Pylint fail : it looks like ci error i will fix pylint is not executed for the deleted file.

Thank you. I'll fix other issues about pylint. :)

**Review by lhs8928 — APPROVED** [review]
LGTM

**Review by SeoHyungjun — APPROVED** [review]
LGTM

Are Application/YOLOv2/PyTorch/yolo.py and yolo_loss.py also V2?
So how about adding v2 to yolo.py and yolo_loss.py?

**Review by myungjoo — APPROVED** [review]

**Pull request merged**
