### PR TITLE
[Fix] Fix semantic tests were not running

### PR DESCRIPTION
**Pull request by zhoonit**
- [Fix] Fix semantic tests were not running

```
This patch fixes semantic tests were not running

**Self evaluation:**
1. Build test: [X]Passed [ ]Failed [ ]Skipped
2. Run test: [X]Passed [ ]Failed [ ]Skipped

Signed-off-by: Jihoon Lee <jhoon.it.lee@samsung.com>

```

### CODE REVIEW

**Comment by zhoonit** [comment]
semantic test wasn't running mainly because
https://stackoverflow.com/questions/54994175/test-p-tests-in-library-do-not-run-when-instantiate-test-case-p-is-called-in-a-s

We can make it link everything with static lib, but that is not desirable solution so tests are unpacked

**Review by kparichay — APPROVED** [review]
LGTM

**Review by jijoongmoon — APPROVED** [review]
LGTM

**Review by lhs8928 — APPROVED** [review]
LGTM

**Review by jijoongmoon — APPROVED** [review]
LGTM

**Pull request merged**
