### PR TITLE
[Ahub] Fix coverage issue

### PR DESCRIPTION
**Pull request by SeoHyungjun**
To resolve AUTO_CAUSES_COPY, auto was changed to const auto&.

### CODE REVIEW

**Review by lhs8928 — APPROVED** [review]
LGTM

**Review by skykongkong8 — APPROVED** [review]
LGTM

**Review by DonghakPark — APPROVED** [review]
LGTM!

**Review by jihochu — APPROVED** [review]
LGTM

**Comment by jihochu** [comment]
coverage > coverity

**Pull request merged**
