### PR TITLE
[test] add test case when a output fc layer is non-trainable

### PR DESCRIPTION
**Pull request by baek2sm**
Add a test case when a output fc layer is non-trainable.

**Self evaluation:**
1. Build test: [x]Passed []Failed []Skipped
2. Run test: [x]Passed []Failed []Skipped

Signed-off-by: Seungbaek Hong <sb92.hong@samsung.com>

### CODE REVIEW

**Review by jijoongmoon — APPROVED** [review]
LGTM.

**Comment by SeoHyungjun** [comment]
LGTM!

**Review by myungjoo — COMMENTED** [review]
unittest_models_v2.tar.gz ??? what's this?

**Comment by baek2sm** [comment]
> unittest_models_v2.tar.gz ??? what's this?

The compressed file includes binary files in which correct answer values for model verification are stored. For example, the result values obtained after executing the same code in the pytorch are made into binary files and used to check if they are the same as the result values obtained from the NNTrainer. Previously, there were 52 binary test files, and I added the following 2 binary files for this test case.

- non_trainable_fc_idx1. nnmodelgolden
- non_trainable_fc_idx2. nnmodelgolden

**Review by jihochu — APPROVED** [review]
LGTM

**Review by myungjoo — APPROVED** [review]

**Pull request merged**
