### PR TITLE
[ Application/bugfix ] Remove unnecessary link @open sesame 08/19 4:43

### PR DESCRIPTION
**Pull request by skykongkong8**
- Previous commit left this unnecessary link and this makes newly-implemented features to fail CI test. Remove accordingly.

**Self evaluation:**
1. Build test:     [X]Passed [ ]Failed [ ]Skipped
2. Run test:     [X]Passed [ ]Failed [ ]Skipped

### CODE REVIEW

**Review by DonghakPark — APPROVED** [review]
LGTM!

**Comment by skykongkong8** [comment]
> LGTM!

Thanks for fast review! 👍

**Review by SeoHyungjun — APPROVED** [review]
LGTM

**Comment by skykongkong8** [comment]
This PR was pointing different issue from the original purpose. Close.

**Pull request closed without merging**
