### PR TITLE
[neuralnet] remove cache related code

### PR DESCRIPTION
**Pull request by lhs8928**
- Currently cache related codes(flushCache/flushCacheExcept) are not included in lts branch so remove the codes.

Signed-off-by: hyeonseok lee <hs89.lee@samsung.com>

### CODE REVIEW

**Review by songgot — APPROVED** [review]
LGTM

**Review by DonghakPark — APPROVED** [review]
LGTM!

**Comment by jihochu** [comment]
I cannot understand why 55082aee29828579c4c02f4c985821c29fd2bfb3 is differ from 18dbe14041bf04917e097c9acd8c38318aef58ab .

**Comment by lhs8928** [comment]
> I cannot understand why [55082ae](https://github.com/nnstreamer/nntrainer/commit/55082aee29828579c4c02f4c985821c29fd2bfb3) is differ from [18dbe14](https://github.com/nnstreamer/nntrainer/commit/18dbe14041bf04917e097c9acd8c38318aef58ab) . Reverting [55082ae](https://github.com/nnstreamer/nntrainer/commit/55082aee29828579c4c02f4c985821c29fd2bfb3) and applying [18dbe14](https://github.com/nnstreamer/nntrainer/commit/18dbe14041bf04917e097c9acd8c38318aef58ab) would be better.

I think applying [18dbe14] to lts cause conflict and while resolve those conflict the cache related code are included.
This force pushed pr did what you recommended that applying [18dbe14] to the reverted lts.

**Pull request merged**
