### PR TITLE
[CI] Replace TAOS -> gitaction & Add more CI

### PR DESCRIPTION
**Pull request by DonghakPark**
This is a pull request to add and modify necessary actions as we completely disable TAOS CI in NNTrainer.
- Add CodeQL to nntrainer (This .yml file, simply copy from nnstreamer's ci file )
- i will add more action for variout test

**Self evaluation:**
1. Build test:	 [X]Passed [ ]Failed [ ]Skipped
3. Run test:	 [X]Passed [ ]Failed [ ]Skipped

### CODE REVIEW

**Review by skykongkong8 — APPROVED** [review]
This PR will definitely improve the way how devs exhange their opinions! Great!

**Review by djeong20 — APPROVED** [review]
👍👍

**Review by myungjoo — APPROVED** [review]

**Review by baek2sm — APPROVED** [review]
LGTM. Thanks!

**Review by jijoongmoon — APPROVED** [review]
LGTM

**Pull request merged**
