### PR TITLE
[ Release ] NNTrainer 0.3.0 Release

### PR DESCRIPTION
**Pull request by jijoongmoon**
NNTrainer v0.3.0 is released.

**Self evaluation:**
1. Build test:	 [X]Passed [ ]Failed [ ]Skipped
2. Run test:	 [X]Passed [ ]Failed [ ]Skipped

Signed-off-by: jijoong.moon <jijoong.moon@samsung.com>

### CODE REVIEW

**Review by kparichay — COMMENTED** [review]
Please update the version number in `/meson.build`.

**Review by kparichay — APPROVED** [review]
LGTM

**Review by zhoonit — APPROVED** [review]
LGTM!

**Comment by alsdk3407** [comment]
55c9

**Pull request merged**
