### PR TITLE
[coverity] fix coverity issue @open sesame 10/02 11:44

### PR DESCRIPTION
**Pull request by djeong20**
This PR resolves the issue by checking what the malloc function returned

**Self-evaluation:**
1. Build test: [X]Passed [ ]Failed [ ]Skipped
2. Run test:   [X]Passed [ ]Failed [ ]Skipped

### CODE REVIEW

**Review by skykongkong8 — APPROVED** [review]
LGTM

**Review by songgot — APPROVED** [review]
LGTM 👍

**Comment by djeong20** [comment]
The current CI failure is a known issue #2486 unrelated to the current patch.

**Comment by skykongkong8** [comment]
> The current CI failure is a known issue #2486 unrelated to the current patch.

Yes.. but #2740 #2739 #2737 #2736 
are showing the same failure for 
```bash
...
[ 1349s] [  FAILED  ] CacheLoaderTest.load_async_02_p
...
```
I think this is not an issue for this PR, but isn't it quite different from what we experienced so far?

**Review by SeoHyungjun — APPROVED** [review]
LGTM

**Review by EunjuYang — APPROVED** [review]
LGTM! Always thank you for checking the coverity issue :)

**Review by lhs8928 — APPROVED** [review]
LGTM

**Review by baek2sm — APPROVED** [review]
LGTM

**Pull request merged**
