### PR TITLE
[#1009] [graph] bug fix on layer names 

### PR DESCRIPTION
**Pull request by kparichay**
Major bug fix on layer names. Layer names were being checked for duplicacy
but not added in the names list. This patch solves that bug.

Also added bug fixes to backbone being added to the graph properly
with appropriate name checkings now.

**Self evaluation:**
1. Build test: [x]Passed [ ]Failed [ ]Skipped
2. Run test: [x]Passed [ ]Failed [ ]Skipped

Signed-off-by: Parichay Kapoor <pk.kapoor@samsung.com>

### CODE REVIEW

**Review by jijoongmoon — APPROVED** [review]
LGTM

**Review by zhoonit — APPROVED** [review]
LGTM, I wonder if we could add a test for this

**Review by lhs8928 — APPROVED** [review]
Great!!

**Comment by kparichay** [comment]
> LGTM, I wonder if we could add a test for this

I will add.

**Pull request merged**
