### PR TITLE
[trivial] fix typo -> nntrainer/Applications/MNIST

### PR DESCRIPTION
**Pull request by DonghakPark**
- Fix typo
- Fix ist --> i <sup>th</sup> for readability

### CODE REVIEW

**Review by lhs8928 — APPROVED** [review]
LGTM except ci issues

**Review by jijoongmoon — APPROVED** [review]
LGTM. How about adding the memory consumption information. If you have a comparison result, then it could be better.

**Comment by jijoongmoon** [comment]
Could you rebase properly? then I will merge this PR.

**Comment by DonghakPark** [comment]
> LGTM. How about adding the memory consumption information. If you have a comparison result, then it could be better.

Yes, That Good idea. Thank you

**Review by songgot — APPROVED** [review]
LGTM

**Pull request merged**
